name: .NET Core Build and Test
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
 
    - name: Build and Test
      uses: ./.github/workflows/actions/build-test

    - name: Organize Artifacts
      run: |
        # Remove the existing artifacts directory if it exists
        rm -rf $GITHUB_WORKSPACE/artifacts || true
        # Create a new artifacts directory
        mkdir -p $GITHUB_WORKSPACE/artifacts
        # Copy the artifacts to the new directory
        cp -r $GITHUB_WORKSPACE/dotnethello/out/* $GITHUB_WORKSPACE/artifacts/

