name: DotNetHelloWorld

on:
  push:
    branches:
      - main

jobs:
  update_dependencies:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'  # Adjust the version to your preference

    - name: Install dotnet-outdated
      run: dotnet tool install --global dotnet-outdated --version 7.3.0  # Use the latest compatible version


    - name: Update Dependencies
      run: dotnet outdated -u

  build_test_deploy:
    runs-on: windows-latest

    needs: update_dependencies

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: dotnet build -c Release

    - name: Run Tests
      run: dotnet test

    - name: Publish
      run: dotnet publish -c Release -o publish_output

    - name: Deploy
      run: echo "Deploying... You can add your deployment steps here."

    - name: Clean Up
      run: echo "Cleaning up...."

    - name: Final Step
      run: echo "All jobs completed!"
