name: DotNetHelloWorld

on:
  push:
    branches:
      - main

jobs:
  build_test_deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: dotnet build -c Release

    - name: Run Tests
      run: dotnet test

    - name: Publish
      run: dotnet publish -c Release -o publish_output

    - name: Deploy
      run: echo "Deploying... You can add your deployment steps here."

    - name: Clean Up
      run: echo "Cleaning up...."

    - name: Final Step
      run: echo "All jobs completed!"
